### ISSUE TITLE
Icone de Fischer en probabilités n'est pas à jour.

### ISSUE THREAD

**Issue by ThatDamGuy** [ArtichOwO/WeebThemeOmega#1]
L'icone des courbes Fischers dans le menu Probabilités est encore de la même couleur que celui d'epsilon.

**Comment by ArtichOwO** [comment]
Ah pardon, j'avais fait un PR sur Omega (https://github.com/Omega-Numworks/Omega/commit/66ea24584c9fbf2dbd057b5c89d0aae4fcbd2164), mais apparement je ne l'ai pas pris en compte sur ce repo ^^" Je le fais le plus vite possible, merci pour votre issue !

**Comment by ArtichOwO** [comment]
976344e3dfc42f2c112306ca8b8d78f9f7a35a41 règle ce problème
